### ISSUE TITLE
Allow DocTypeGridEditorHelper.ConvertValueToContent from Examine GatherNodeTypeData event

### ISSUE THREAD

**Issue by nvisage-gf** [leekelleher/umbraco-doc-type-grid-editor#25]
Calling this helper method during indexing causes a `NullReferenceException` due to being wrapped in a caching call.

Stack trace below:

```
Exception: Object reference not set to an instance of an object. - StackTrace:    at     Umbraco.Core.Cache.HttpRequestCacheProvider.get_ContextItems()
   at Umbraco.Core.Cache.HttpRequestCacheProvider.get_WriteLock()
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String docTypeAlias, String dataJson) in d:\Work\Code\umbraco-doc-type-grid-editor\Src\Our.Umbraco.DocTypeGridEditor\Helpers\DocTypeGridEditorHelper.cs:line 27
```

Moving the getGetItem delegate function to a named function, trapping the exception and calling the named function allows the helper to return `IPublishedContent` which can then be cast to correct Doc Type (e.g. via ModelsBuilder) for further processing (e.g. indexing).

Example pull request incoming for feedback/discussion.

**Comment by nvisage-gf** [comment]
Example code to index the `Text` property of a Grid Doc Type with the alias of BreakoutBox; note the rest of the OnExamineGatheringNodeData method excluded for brevity; additionally `e.GetGridModel()` is just a helper extension method that returns a de-serialised GridDataModel

C#```

    case "BreakoutBox":
        {
            dynamic model = ctrl.JObject;
            string id = model.value.id.ToString();
            string docType = model.value.docType.ToString();
            string value = model.value.value.ToString();
            var content = DocTypeGridEditorHelper.ConvertValueToContent(id, docType, value);
            var box = new BreakoutBox(content);
            text = box.Text;
            if (!string.IsNullOrWhiteSpace(text))
            {
                gridContent.AppendLine(text);
            }
            break;
        }
```
