### ISSUE TITLE
User doesn't select a doc type - exception shown

### ISSUE THREAD

**Issue by cheeseytoastie** [leekelleher/umbraco-doc-type-grid-editor#28]
If the editor closes the doc type select side panel by clicking cancel then the grid shows an empty block with click to insert item (which is correct). If the editor doesn't select a block but publishes the page an exception is shown to visitors.

System.Exception: ContentTypeService failed to find a content type with alias "".
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String docTypeAlias, String dataJson)
   at ASP._Page_app_plugins_doctypegrideditor_render_doctypegrideditor_cshtml.Execute() in c:\Users\Steve\Documents\GitHub\SpringInto\SpringInto\App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditor.cshtml:line 12
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at System.Web.Mvc.BuildManagerCompiledView.Render(ViewContext viewContext, TextWriter writer)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.HtmlHelper.RenderPartialInternal(String partialViewName, ViewDataDictionary viewData, Object model, TextWriter writer, ViewEngineCollection viewEngineCollection)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model)
   at ASP._Page_Views_Partials_grid_editors_base_cshtml.Execute() in c:\Users\Steve\Documents\GitHub\SpringInto\SpringInto\Views\Partials\Grid\Editors\Base.cshtml:line 20

**Comment by cheeseytoastie** [comment]
I patched this by checking for an empty doctype in the Render DocTypeGridEditor.cshtml

```
@using System.Web.Mvc.Html
@using Our.Umbraco.DocTypeGridEditor.Helpers
@using Our.Umbraco.DocTypeGridEditor.Web.Extensions
@inherits Umbraco.Web.Mvc.UmbracoViewPage<dynamic>
@if (Model.value != null)
{
    string id = Model.value.id.ToString();
    string docType = Model.value.docType.ToString();
    string value = Model.value.value.ToString();
    string viewPath = Model.editor.config.viewPath.ToString();
    
    if(docType != "")
    { 
        var content = DocTypeGridEditorHelper.ConvertValueToContent(id, docType, value);
    
        @Html.RenderDocTypeGridEditorItem(content, viewPath)
    }
} 
```

**Comment by mattbrailsford** [comment]
@cheeseytoastie would be awesome if you could submit that as a PR

**Comment by cheeseytoastie** [comment]
I *think* I've done that right... to the develop branch anyhow?

**Comment by mattbrailsford** [comment]
Yup, perfect. Thank you for that. Really appreciated.
