### ISSUE TITLE
Handle blank doctype grid value in cell

### ISSUE THREAD

**Issue by BarryFogarty** [leekelleher/umbraco-doc-type-grid-editor#30]
If you have say, 3 cells in your row all of which can have DTGE content, but one or more of these cells does not contain content, you get errors in your log as follows:

ERROR Umbraco.Core.UmbracoApplicationBase - An unhandled exception occurred
System.Exception: ContentTypeService failed to find a content type with alias "".
   at Umbraco.Core.Cache.HttpRequestCacheProvider.GetCacheItem(String cacheKey, Func`1 getCacheItem)
   at Our.Umbraco.DocTypeGridEditor.Helpers.DocTypeGridEditorHelper.ConvertValueToContent(String id, String docTypeAlias, String dataJson)
   at ASP._Page_App_Plugins_DocTypeGridEditor_Render_DocTypeGridEditorPreviewer_cshtml.Execute() in c:\Projects\TescoAlumni.v7\src\TescoAlumni.Site\App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditorPreviewer.cshtml:line 11

This is because the relevant item in the XML cache has docType: "".

It would be nice to handle this scenario in the previewer so it does not pollute the log with red herring exceptions.  I'll submit a simple PR - unless there's a good reason not to handle the blank docType property?

**Comment by leekelleher** [comment]
Thanks @BarryFogarty - sorry for the delay in replying.  This has been fixed with PR #17, for upcoming release.
