### ISSUE TITLE
doesnt work with modelsbuilder

### ISSUE THREAD

**Issue by ninjaonsafari** [leekelleher/umbraco-doc-type-grid-editor#44]
Hi

We are using the Umbraco 7.4.1 with the new models builder.
But it seems it cannot convert to the `DetachedPublishedContent` to our generated models.

    Umbraco.Web.Mvc.ModelBindingException: Cannot bind source content type Our.Umbraco.DocTypeGridEditor.Models.DetachedPublishedContent to model type Opten.Demo.Web.Models.CallToActionButton.

Is there something wrong with the `DetachedPublishedContent`? 
With an IPublishedContent it works.

Thanks!

**Comment by mattbrailsford** [comment]
I believe the models builder does not work recursively on "fake" IPublishedContent nodes which the DTGE model is (it's not a real node in the content tree). I think you'd need to tell the models builder to ignore that property and override / populate it yourself (TIP You could use Ditto to do the mapping).

**Comment by ninjaonsafari** [comment]
as a quick fix.

    @inherits UmbracoViewPage<IPublishedContent>
    @if (Model != null)
    {
	    var model = new CallToActionButton(Model);

    }

**Comment by leekelleher** [comment]
Closing.

Unsure what DTGE could do differently to support ModelsBuilder binding.
(Answers on a postcard welcome :smiley:)

**Comment by leekelleher** [comment]
... that said, I got curious... took a look at Umbraco's `RenderModelBinder` code and it uses `TryConvertTo<T>()`, see here:

https://github.com/umbraco/Umbraco-CMS/blob/release-7.4.1/src/Umbraco.Web/Mvc/RenderModelBinder.cs#L68

This means that a custom TypeConverter could be developed to convert from `DetachedPublishedContent` into the target type.

A generic solution could most likely be developed, but would take time/effort/motivation. :see_no_evil::hear_no_evil::speak_no_evil:

**Comment by ninjaonsafari** [comment]
We are using now this solution for the moment.

	using System;
	using System.Web.Mvc;
	using Umbraco.Core.Models.PublishedContent;
	using Umbraco.Web.Mvc;

	namespace Opten.Modules.Web.Mvc
	{
		public abstract class ModulesViewPage<TModel> : UmbracoViewPage<TModel> where TModel:PublishedContentModel
		{
			// maps model
			protected override void SetViewData(ViewDataDictionary viewData)
			{
				viewData.Model = (TModel)Activator.CreateInstance(typeof(TModel), new object[] { viewData.Model });

				// set the view data
				base.SetViewData(viewData);
			}
		}
	}

**Comment by AussieInSeattle** [comment]
@ninjaonsafari - thanks for the code - helped me fix the issue so that DTGE works with the Models Builder - really should be part of the DTGE I think @leekelleher ?

**Comment by leekelleher** [comment]
The ViewPage code? I'm not sure how that helps with ModelsBuilder. From my understanding it's only for rendering the view and tied to using `PublishedContentModel` objects (which I don't personally).

Also not sure of where that code would live inside DTGE and how to enforce users to inherit their views from it.

**Comment by AussieInSeattle** [comment]
No, the code above for the ModulesViewPage class - maybe there is another fix, but on my DTGE Views that use ModelsBuilder instead of using the default:
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ImageWithArticleCtaoverlay>
I now use:
@inherits MyCustomAssembly.ModulesViewPage<ContentModels.ImageWithArticleCtaoverlay>

Which fixes the binding exception mentioned at the top of the issue and means I can use ModelsBuilder with DTGE Views.  So was just saying that the above class should be in your code rather than having to include it in my own assembly?  And then I just change the inherits line in the view to hook it up?

**Comment by mattbrailsford** [comment]
I don't believe the ModulesViewPage class is the "right" fix though. It's basically a quick fix that gets around the real problem so it would be mistake to include that in DTGE and promote it as "the solution". The real fix needs to be to get DTGE to work with models builder so that you wouldn't need that at all. As Lee said, a TypeConverter might be the solution, but it's finding the time to look into it properly.

Any guidance from someone with a bit more ModelsBuilder knowledge would be highly appreciated here.

**Comment by skttl** [comment]
@ninjaonsafari can you elaborate on how you got it working?

I tried your first quickfix, but I still get `Cannot bind source content type Our.Umbraco.DocTypeGridEditor.Models.DetachedPublishedContent to model type Umbraco.Web.PublishedContentModels.DtgeLinkGrid`.

I also tried you second one, and set `@inherits ModulesViewPage<DtgeLinkGrid>` in the top of my view, but still no luck.

**Comment by ninjaonsafari** [comment]
we are using the exact code from my second post.
Whats the error you get?
Can you create an instance from `DtgeLinkGrid` with the `DetachedPublishedContent`?

**Comment by skttl** [comment]
@ninjaonsafari 

This is the stack trace I get:
```
Umbraco.Web.Mvc.ModelBindingException: Cannot bind source content type Our.Umbraco.DocTypeGridEditor.Models.DetachedPublishedContent to model type Umbraco.Web.PublishedContentModels.DtgeLinkGrid.
   at Umbraco.Web.Mvc.RenderModelBinder.ThrowModelBindingException(Boolean sourceContent, Boolean modelContent, Type sourceType, Type modelType)
   at Umbraco.Web.Mvc.RenderModelBinder.BindModel(Object source, Type modelType, CultureInfo culture)
   at Umbraco.Web.Mvc.UmbracoViewPage`1.SetViewData(ViewDataDictionary viewData)
   at System.Web.Mvc.RazorView.RenderView(ViewContext viewContext, TextWriter writer, Object instance)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at Our.Umbraco.DocTypeGridEditor.Web.Extensions.HtmlHelperExtensions.RenderDocTypeGridEditorItem(HtmlHelper helper, IPublishedContent content, String editorAlias, String viewPath, String previewViewPath)
   at ASP._Page_app_plugins_doctypegrideditor_render_doctypegrideditor_cshtml.Execute() in c:\Workspaces\Web\App_Plugins\DocTypeGridEditor\Render\DocTypeGridEditor.cshtml:line 28
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.Mvc.WebViewPage.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at Umbraco.Core.Profiling.ProfilingView.Render(ViewContext viewContext, TextWriter writer)
   at System.Web.Mvc.Html.PartialExtensions.Partial(HtmlHelper htmlHelper, String partialViewName, Object model, ViewDataDictionary viewData)
   at ASP._Page_Views_Partials_grid_editors_base_cshtml.Execute() in c:\Workspaces\Web\Views\Partials\Grid\Editors\Base.cshtml:line 20
```

Looks like it doesnt even get into the partial view

**Comment by ninjaonsafari** [comment]
Hi here is what we are using in prod.
https://gist.github.com/ninjaonsafari/13d8b6a2e420884445dd3fe26fa0c39a

**Comment by skttl** [comment]
Thanks @ninjaonsafari 

Are you using Skybrud.GridData?

**Comment by ninjaonsafari** [comment]
@skttl Yep.

**Comment by skttl** [comment]
Ok, I'll look into it :)

**Comment by skttl** [comment]
Still getting the same stack trace :(

What version of DTGE are you using @ninjaonsafari ?

**Comment by ninjaonsafari** [comment]
hmm i think its version 2.5

**Comment by ninjaonsafari** [comment]
@skttl just updated to the latest version and it works.
I dont know whats wrong in your solution.

**Comment by skttl** [comment]
Hey, got it working, was screwing around in the wrong partial :)
